# Data Exploration

## Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

## Load data

In [2]:
# read data from google drive
from google.colab import drive
drive.mount('/content/drive')

customer_df = pd.read_csv("/content/drive/MyDrive/dataset/customer_data_dirty.csv")
geolocation_df = pd.read_csv("/content/drive/MyDrive/dataset/geolocation_dirty.csv")
order_item_df = pd.read_csv("/content/drive/MyDrive/dataset/order_item_dirty.csv")
order_payments_df = pd.read_csv("/content/drive/MyDrive/dataset/order_payment_dirty.csv")
order_reviews_df = pd.read_csv("/content/drive/MyDrive/dataset/order_review_dirty.csv")
orders_df = pd.read_csv("/content/drive/MyDrive/dataset/orders_dataset_dirty.csv")
product_category_name_df = pd.read_csv("/content/drive/MyDrive/dataset/product_category_dirty.csv")
products_df = pd.read_csv("/content/drive/MyDrive/dataset/products_dirty.csv")
seller_df = pd.read_csv("/content/drive/MyDrive/dataset/seller_dirty.csv")

# customer_df = pd.read_csv("../dataset/customer_data_dirty.csv")
# geolocation_df = pd.read_csv("../dataset/geolocation_dirty.csv")
# order_item_df = pd.read_csv("../dataset/order_item_dirty.csv")
# order_payments_df = pd.read_csv("../dataset/order_payment_dirty.csv")
# order_reviews_df = pd.read_csv("../dataset/order_review_dirty.csv")
# orders_df = pd.read_csv("../dataset/orders_dataset_dirty.csv")
# product_category_name_df = pd.read_csv("../dataset/product_category_dirty.csv")
# products_df = pd.read_csv("../dataset/products_dirty.csv")
# seller_df = pd.read_csv("../dataset/seller_dirty.csv")

Mounted at /content/drive

In [3]:
print("Customer Data:")
display(customer_df.head())

print("Geolocation Data:")
display(geolocation_df.head())

print("order item Data:")
display(order_item_df.head())

print("order payment Data:")
display(order_payments_df.head())

print("orders Data:")
display(orders_df.head())

Customer Data:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409.0,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790.0,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151.0,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775.0,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,NaN,13056.0,campinas,SP

Geolocation Data:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037.0,-23.545621,-46.639292,sao paulo,NaN
1,1046.0,-23.546081,-46.644820,NaN,SP
2,1046.0,-23.546129,-46.642951,sao paulo,SP
3,1041.0,-23.544392,-46.639499,sao paulo,SP
4,1035.0,-23.541578,-46.641607,sao paulo,SP

order item Data:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1.0,credit_card,8.0,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1.0,credit_card,1.0,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1.0,credit_card,1.0,65.71
3,ba78997921bbcdc1373bb41e913ab953,1.0,credit_card,8.0,107.78
4,42fdf880ba16b47b59251dd489d4441a,1.0,credit_card,NaN,NaN

order payment Data:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1.0,credit_card,8.0,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1.0,credit_card,1.0,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1.0,credit_card,1.0,65.71
3,ba78997921bbcdc1373bb41e913ab953,1.0,credit_card,8.0,107.78
4,42fdf880ba16b47b59251dd489d4441a,1.0,credit_card,NaN,NaN

orders Data:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,NaN,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

## Merging Data

Merge data `customer_df` with `orders_df`

In [ ]:
# customer_orders_df = pd.merge(customer_df, orders_df, on="customer_id", how="inner")

# # save data to csv
# customer_orders_df.to_csv("../dataset/customer_orders.csv", index=False)

In [ ]:
# customer_orders_df = pd.read_csv("../dataset/customer_orders.csv")

In [4]:
customer_orders_df = pd.read_csv("/content/drive/MyDrive/dataset/customer_orders.csv")

In [5]:
customer_orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25591612 entries, 0 to 25591611
Data columns (total 12 columns):
 #   Column                         Dtype
---  ------                         -----
 0   customer_id                    object
 1   customer_unique_id             object
 2   customer_zip_code_prefix       float64
 3   customer_city                  object
 4   customer_state                 object
 5   order_id                       object
 6   order_status                   object
 7   order_purchase_timestamp       object
 8   order_approved_at              object
 9   order_delivered_carrier_date   object
 10  order_delivered_customer_date  object
 11  order_estimated_delivery_date  object
dtypes: float64(1), object(11)
memory usage: 2.3+ GB

In [6]:
customer_orders_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409.0,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05 00:00:00
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790.0,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06 00:00:00
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151.0,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13 00:00:00
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775.0,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10 00:00:00
4,4f2d8ab171c80ec8364f7c12e35b23ad,NaN,13056.0,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,NaN,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15 00:00:00

In [7]:
# prompt: buatkan script untuk menghapus baris data di variable customer_orders_df menjadi hanya sebanyak 70.000 data saja dengan menggunakan metode drop

# Drop rows to limit the DataFrame to 70,000 rows
customer_orders_df = customer_orders_df.head(70000)

# Display info to verify the change
customer_orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    476 non-null    object
 1   customer_unique_id             54893 non-null  object
 2   customer_zip_code_prefix       69977 non-null  float64
 3   customer_city                  69985 non-null  object
 4   customer_state                 65817 non-null  object
 5   order_id                       66488 non-null  object
 6   order_status                   66359 non-null  object
 7   order_purchase_timestamp       66752 non-null  object
 8   order_approved_at              65961 non-null  object
 9   order_delivered_carrier_date   64897 non-null  object
 10  order_delivered_customer_date  64263 non-null  object
 11  order_estimated_delivery_date  66561 non-null  object
dtypes: float64(1), object(11)
memory usage: 6.4+ MB